version: "3.8"

services:
  api:
    build: .
    container_name: my_api
    ports:
      - "8000:8000"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    pid: host
    network_mode: host
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    restart: alwaysv|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'