version: "3.8"

services:
  api:
    build: .
    container_name: my_api
    ports:
      - "8000:8000"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    pid: host
    network_mode: host
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'